### ISSUE TITLE
[T1] 프로젝트 팀 목표, 개인 목표

### ISSUE THREAD

**Issue by shimguh** [HW-UMUL/main#1]
### 팀 목표
1) 대략 2주 정도를 한 사이클 시간으로 설정해 작업.
2) 사이클이 끝나면 부족한 부분 보안.
3) 팀원 모두가 프로젝트 프로세스 전 과정 경험.
3-1) 테스트 작업
3-2) (시간 허용 범위 안에서) 팀원 기능 구현 파트 맡아 작업
4) 코드 작업보다 팀원 질문(소통) 우선
5) 코드 규약 작성(대소문자, 케이스 정리 등)
6) 코드 주석 철저히
7) 팀 회의 시간 정하기(오전 할일, 하루 일정 회고 등)
8) main 브런치 이외 본인 브런치에 만들어진 PR은 본인이 합친다.

### 개인 목표
- 민우 : 백엔드와 프론트엔드에 대해 더 깊게 이해하기, CI/CD 경험해보기, 서버에 대한 지식 높이기, 보안과 테스트에 대해 신경쓰기
- 경민 : 프로젝트 전체 이해하기, 차분히 천천히 진행, Issue 및 PR 활용 최대화 하기, 매일 팀프로젝트 회고하고 정리하기
- 대호 : 컴포넌트 기반 개발 이해
- 규혁 : 팀 프로젝트 경험과 개발 이해하기, git 사용 이해하고 익숙해지기

### 개발 목표

**Comment by papercrane55123** [comment]
![LGTM](https://i.lgtm.fun/2p3c.png)
