### ISSUE TITLE
[T1] MVP를 위한 프로젝트 선행기술

### ISSUE THREAD

**Issue by papercrane55123** [HW-UMUL/main#2]
### (MVP)선행 기술 : 무엇을 할 것인가?
민우 : 왜, 어떻게 구성 / 필요한 기술 / 검색 시스템 위주로 / 특허쪽에서는 ui가 어떻게 구성되어 있는지
대호 : 컨플루언스 참고 /
규혁 :
경민 : 지식 기준잡기 /

**Comment by minu1215** [comment]
소셜 네트워크 서비스 기반의 4세대 지식관리시스템 설계 방안
https://www.dbpia.co.kr/journal/articleDetail?nodeId=NODE06668091
![image](https://github.com/final-kms/main/assets/44054359/2f6bb05f-1532-4b75-82a1-52e43ad0c63e)

**Comment by minu1215** [comment]
건설프로젝트 지식블로그를 활용한 지식관리시스템 및 그방법
Construction Project knowledge blog based Knowledge management system and method
출원번호 : 1020080057779

AI에 의한 재난안전지식 통합관리시스템 (A system for integrated management of disaster safety knowledge by AI)
출원번호 : 1020220127828

지식체계 관리 시스템 및 방법 (System and method for management of knowledge system)
출원번호 : 1020140188963

숙련자 상담 데이터 및 자유 발화 감정 분석에 기반한 AI 기능이 부가된 CS를 위한 지식 관리 시스템 (KNOWLEDGE MANAGEMENT SYSTEM FOR CUUSTOMER SERVICE WITH AI FUNCTION BASED ON EXPERT CONSULTATION DATA AND FREE SPEECH EMOTION ANALYSIS)
출원번호 : 1020220134518

지식 컨텐츠 기반 상담 시스템 (Knowledge content-based consulting system)
출원번호 : 1020220012515

**Comment by minu1215** [comment]
https://hiverhq.com/blog/free-knowledge-base-software

**Comment by papercrane55123** [comment]
디자인 교육 향상을 위한 지식 관리 시스템에 관한 연구(전체적인 틀을 확인하기에 좋은 논문입니다)
https://woosong.dcollection.net/public_resource/pdf/200000647958_20240304123314.pdf

**Comment by pdh4869** [comment]
컨플루언스와 다른 시스템의 기능 비교 
https://www.atlassian.com/ko/software/confluence/comparison/confluence-vs-gdocs
![image](https://github.com/final-kms/main/assets/76561901/d881858b-2f02-4d3e-867d-d169a50a7271)
위 이미지의 기능 정도가 참고 가능할 것 같습니다.

**Comment by pdh4869** [comment]
![image](https://github.com/final-kms/main/assets/76561901/0938d4fc-a2dd-4500-9c5f-6731e4d1d87d)

https://www.dbpia.co.kr/journal/detail?nodeId=T15829458
kms의 효과 등을 참고할 수 있을 것 같습니다.

**Comment by minu1215** [comment]
지식관리시스템 특성이 지식공유 의도에 미치는 영향: 지식공유 분위기와 신뢰성의 조절 효과
https://www.dbpia.co.kr/journal/articleDetail?nodeId=NODE11169131

지식관리시스템 활용 지원이 기술수용 및 정보제공 행동에 미치는 영향: 상호 피드백과 협력 지향성의 역할
https://www.dbpia.co.kr/pdf/pdfView.do?nodeId=NODE11617110

지식관리시스템 품질과 업무 환경이 조직원의 지식공유에 미치는 영향: 기술수용모델의 확장
https://www.dbpia.co.kr/pdf/pdfView.do?nodeId=NODE11169340

지식관리시스템 도입 필요성과 효율적 병원 전산 운영
https://www.dbpia.co.kr/pdf/pdfView.do?nodeId=NODE07040568

기업용 SNS 이용이 업무성과에 미치는 영향의 국가 간 비교연구 - 커뮤니케이션 수준의 매개효과와 국적의 조절효과를 중심으로 -
https://www.dbpia.co.kr/journal/articleDetail?nodeId=NODE09388345
