### ISSUE TITLE
PM 회의 정리

### ISSUE THREAD

**Issue by papercrane55123** [HW-UMUL/main#22]
1. 멘토링 주의 사항
\- 기획안 같은 문서는 회의 이전에 미리 공유
\- 질문 사항이 있으면 미리 정리해서 공유
\- 멘토님 성향에 맞춰 진행할 것
\- 토요일에 보는 것은 부담을 가지실 수 있으니 지양할 것
\- 부담 주지 말것

2. 프로젝트 관련 내용
\- 기능은 간소화(만약 간소화 할 수 없는 부분이 생긴다면(회원 등) 더미 데이터를 두는 방향으로 진행)
\- 참신한 기능 추가(기존의 것 답습하는 방식 x)
\- 여러번 배포하고 수정하는 시간적 여유 가지기
\- 설명과 논의는 근거를 바탕으로
\- 시스템 전반적인 이해도를 높이고자 노력할 것(개념적 회의 깊이있게)
\- 최종 발표에서 받을 수 있는 질문(왜 일정대로 진행하지 않고 팀 독단으로 진행했나? 등) 생각해보기 
\- 가상의 대상 고객 설정해 맞춰보기

\* 다음 PM 회의는 1팀에서 진행할 것. Issue 올리고 의견 맞춰보기

**Comment by pySatellite** [comment]
잘 정리해 주셔서 감사합니다.
이번에는 제가 본류 이슈에 링크 걸어 둘께요
