### ISSUE TITLE
[T1] 요구사항 version 1

### ISSUE THREAD

**Issue by pdh4869** [HW-UMUL/main#3]
### 질문/답변
  - 이용자는 게시글을 작성할 수 있어야 한다.
  - 이용자는 게시글에 대해 답변을 작성할 수 있어야 한다.
  - 이용자는 게시글에 대해 추천을 할 수 있어야 한다.
  - 이용자는 답변에 대해 추천을 할 수 있어야 한다.
  - 게시글에 대해 공개 범위를 설정할 수 있어야 한다.
  - 첨부 파일을 업로드 할 수 있어야 한다.(+ 마크다운 처리)
  - 권한이 부여된 이용자는 게시글을 수정/삭제 할 수 있어야 한다.
  - 권한이 부여된 이용자는 게시글을 수정/삭제 할 수 있어야 한다.
  - 이용자는 태그를 작성할 수 있어야 한다.
  - 이용자는 카테고리를 선택할 수 있어야 한다.
  - 이용자는 멘션(@)이 가능해야 한다.
  - 멘션 처리된 이용자에 대해 알림을 보낸다.
  - 이용자는 게시글을 즐겨찾기할 수 있다.

### 위키
  - 이용자는 글을 작성할 수 있어야 한다.(+ 마크다운 처리)
  - 이용자는 타이틀(제목)을 작성할 수 있어야 한다.
  - 이용자는 태그를 작성할 수 있어야 한다.
  - 이용자는 카테고리를 선택할 수 있어야 한다.
  - 이용자는 첨부 파일을 업로드 할 수 있어야 한다.(+ 마크다운 처리)
  - **실시간 공동 작성이 가능하도록 한다. - 도전과제**
  - 이용자 업무 수행에 대한 Log가 기록되어야 한다.
  - 이용자는 글의 수정/삭제 가능하여야 한다. 
  - 이용자는 글을 즐겨찾기할 수 있다.
  - 인기순으로 정렬 가능해야 한다.

### 검색
  - 연관된 검색어가 검색되어야 한다.
  - 검색 질문의 동사와 명사만 추출한다.
  - 검색 기록을 확인할 수 있어야 한다.
  - 카테고리별 검색을 할 수 있어야 한다.
  - 태그별 검색을 할 수 있어야 한다.

### 조직
  - 이용자는 조직을 만들 수 있다.
  - 조직 내에서 다른 사람을 초대, 권한 부여가 가능해야 한다.
  - 조직의 공개 여부 설정이 가능해야 한다.

### 채팅
  - 이용자는 채팅이 가능해야 한다.
  - 이용자는 채팅방을 만들 수 있어야 한다.
  - 조직에 대하여 단체 채팅이 가능해야 한다.
  - 채팅 owner가 이용자를 초대할 수 있다.
  - 채팅 이용자는 채팅으로부터 언제든지 나올 수 있다.
  - 보낸 채팅을 본인이 삭제할 수 있어야 한다.

### 마이페이지
  - 본인이 작성한 게시글을 볼 수 있도록 한다
  - 본인이 작성한 답변을 볼 수 있도록 한다.
  - 날짜/추천 수 등으로 정렬할 수 있도록 한다.
  - 개인 정보를 볼 수 있도록 한다.
  - 조직 초대 정보를 확인할 수 있도록 한다.
  - 즐겨찾기 정보를 확인할 수 있도록 한다.
  - 이용자가 추천한 게시글, 답변, 위키를 확인할 수 있어야 한다.
  - 개인정보 수정/탈퇴가 가능하도록 한다.

### 관리자 
  - 관리자는 작성자에 상관없이 수정 및 삭제가 가능하다.
  - 관리자는 공지사항 게시글을 작성할 수 있다.
  - 관리자는 이용자에게 권한 부여가 가능해야 한다.

###  SNS 기반 인터페이스 설계
  - 인기순, 관련된 순을 나열한다.
  - 팔로우 기능이 있어야 한다.
  - 필요 페이지의 스크롤 전까지 데이터를 갱신하지 않는다.

### 로그인/로그아웃
  - 각자의 아이디/비밀번호로 직원을 식별할 수 있도록 한다.
  - 보안을 위해 JWT를 사용한다.
  - 보안을 위해 추가적인 조치를 취한다.

### 알고리즘 (도전과제)
  - **머신러닝 알고리즘을 사용하여 검색 정확성/연관성을 향상시킨다.**
  - **신경망 알고리즘을 사용하여 검색 정확성/연관성을 향상시킨다.**

**Comment by papercrane55123** [comment]
![LGTM](https://i.lgtm.fun/2ps3.png)
