### ISSUE TITLE
[T1] 24.03.11 2회차 멘토링 정리 및 회고

### ISSUE THREAD

**Issue by shimguh** [HW-UMUL/main#39]
db
- 생성자, 수정자, 수정일자 넣기
- 네이밍 규칙 정하기(복합어)
- 날짜, 시간(항목 따라, 범위)
- 사이즈 정하기(varchar는 상관없는 경우 있지만 char는 정하는게 좋음)
- 일반적으로 같은건 동일한 이름 사용(외래키 받아올 때) -> 정리 필요
- 네이밍 직관적으로(date -> create_date)
- 게시글의 경우 재귀 / 분리 등으로 가능
- 좋아요와 다른 테이블 관계 다시 확인(1대다)
- WIKI_LOG 복구 용도일 경우 외래키 전체 필요
- 조인 테이블 기본키는 생성자 철학 차이
- msa db 경우 조인 테이블 모두 구현하면 복잡해짐, 조인 테이블이 많다 -> msa가 맞는가?
- msa 분리는 기술 분야보다 업무 담당자가 하는게 좋음

기획서
- 기대 효과가 중요

요구사항
- 검색-동사와 명사 추출 부분 -> 자연어 검색을 지원한다 수정
- 검색 대상 정의(질문, 내용, ...)
- 조직-탈퇴, 추방 기능 추가
- 조직의 정의, 목적 필요
- 보안을 위해 암호화 사용

서비스 기획(UI 설계)
- UI 설계 내용 디테일 필요
- 인프라 환경 구축
- 크롬 개발자 도구 활용

[같은 내용 자세히 보기](https://blog.naver.com/mini_crane_/223380350040)

**Comment by papercrane55123** [comment]
목요일 회사로 직접 방문하여 멘토링하는 것에 대해 의견 공유 필요
