### ISSUE TITLE
[T1]담당자 정하기

### ISSUE THREAD

**Issue by papercrane55123** [HW-UMUL/main#5]
- [x] : 라벨 담당자(마일스톤 등)
- [x] : last-dance PR 담당자
- [x] : 회고 및 정리

**Comment by pdh4869** [comment]
제가 라벨 하겠습니다

**Comment by shimguh** [comment]
PR은 제가 하겠습니다

**Comment by papercrane55123** [comment]
회고 및 정리는 제가 맡아서 하겠습니다.
