### ISSUE TITLE
수정 사항 및 필요 작업

### ISSUE THREAD

**Issue by pdh4869** [HW-UMUL/main#56]
## 수정 사항
 ~~글 목록에서 작성 시간, 작성자 불러올 때 첫 작성을 기준으로 함 (wiki_log 테이블에서 데이터 불러오기)~~
- [x] 글 수정 시 내용이 바로 안나옴
- [x] 시간이 12시간제로 나와 24시간제로 변경
- [x] 수정 폼에서 어느 버튼을 눌러도 wiki log가 추가되는 현상 수정 (submit.prevent 및 수정 버튼 외 버튼 type="button"으로)
- [x] 수정 폼에서 에디터 적용 시 content 부분에 내용이 안나옴
- [x] 엔터 누르면 에디터가 분리되는 현상 fix
- [x] 에디터 자동 줄바꿈
- [x] 좋아요/추천수 순위 매길 때 조인, 서브쿼리 사용 필요하다고 생각함 (Jpa에서 사용 불가하다고 함, 해결 방안 필요)
- [x] 마크다운 활용으로 글에 효과를 주기 위한 에디터 적용
- [x] 글 리스트 페이지네이션 
- [x] 더 보기 버튼 만들기 (로그) 
- [x] 카테고리별 게시글 필터링

## 필요 작업
- [ ] 로그에서 wiki 글 변경자 받아오기
- [ ] 로그 클릭 시 그 로그로 update할 수 있도록 만들기(백업?)
- [ ] 로그 변경 부분만 표시하기
- [ ] 카테고리 중복 제거
- [ ] 세부 카테고리 
- [ ] 로그인한 사용자별 수정/삭제 버튼 렌더링 구현 - v-if 활용

**Comment by papercrane55123** [comment]
![LGTM](https://i.lgtm.fun/2qhc.png)

감사합니다 ㅎㅎ

**Comment by pdh4869** [comment]
좋아요/추천수 순위 매기기  => vue 내 함수 선언하여 해결

**Comment by pdh4869** [comment]
글 수정 시 내용이 바로 안나옴 => 데이터를 받아와 저장하는 변수를 reactive로, 데이터를 받아오는 작업을 onMounted()로 실행하여 데이터를 받아와 바로 렌더링하도록 함.

**Comment by pdh4869** [comment]
수정 폼에서 에디터 적용 시 content 부분에 내용이 안나옴 => onMounted와 props의 시간 차이때문에 발생한 문제. 임시로 타임아웃을 줘서 해결

**Comment by pdh4869** [comment]
- 엔터 누르면 에디터 분리되는 현상 fix

```
npm install @tiptap/extension-hard-break

import HardBreak from '@tiptap/extension-hard-break'

const CustomHardBreak = HardBreak.extend({
  addKeyboardShortcuts() {
    return {
      Enter: () => this.editor.commands.setHardBreak(),
    }
  },
})
```

**Comment by pdh4869** [comment]
자동 줄바꿈 - 에디터 width 지정 x. 하려면 div 활용
