### ISSUE TITLE
[T1] 24.03.26 7회차 멘토링 정리 및 회고

### ISSUE THREAD

**Issue by pdh4869** [HW-UMUL/main#75]
자소서 관련
   - 지원동기에서 자기 이야기를 먼저 하라
   - 자신만의 특색 보여주기 (처음부터 적으면 좋을 것 같다)
   - 소제목 적기
   - 지원 직무에 타겟팅하여 적기
   - 항목에 대한 일관성 유지 
   - 활동에 대한 명칭 작성 
   - 두괄식 작성 (핵심/결론부터 작성)
   - 세부적인 설명
   - 시기/기간/규모 등의 정보 작성
   - 수치 표기
   
  
  - 향후 계획  3~5년 정도, 구체적으로 적기 (기업에 대한 관심, 기업분석 등)

+ 현대/삼성/한화 등 전통적 대기업은 머리 깎아야 함

------------------------------------------------------------------------------------

프로젝트 
- 서비스 구현 후 고도화(이중화/MSA)
- 인프라 구축 먼저

**Comment by papercrane55123** [comment]
감사합니다. 최고에요~~
![LGTM](https://i.lgtm.fun/2qkp.gif)
