### ISSUE TITLE
프로젝트 일정 최종 v2.1

### ISSUE THREAD

**Issue by papercrane55123** [HW-UMUL/main#82]
![image](https://github.com/final-kms/main/assets/150432433/7ac5a63f-5dc3-4334-8871-5cfc24563400)

[WBS 문서 보기](https://drive.google.com/drive/folders/19ArjdC_CfmE8emerWVEXWo039VPOis8X)
## 4월 첫째주 (App, MSA, 검색(AI), 관리자 페이지, 프론트, 검색 기능 통합)
- [ ] 민우 : APP, 검색 추가
- [ ] 규혁 : 관리자 페이지
- [ ] 대호 : MSA
- [ ] 경민 : 검색(AI)

- 2일 개인 작업 수행
- 3일 개인 작업 수행 
- 4일 개인 작업 수행 / 배포(STG) / README 정리
- 5일 개인 작업 수행 

## 4월 둘째주 (권한 정리, MSA, TEST(성능 테스트), 인터페이스 정리, 프론트)
- [ ] 민우 : APP, 검색 추가, MSA
- [ ] 규혁 : 관리자 페이지
- [ ] 대호 : MSA
- [ ] 경민 : 검색(AI), README.md, WBS 정리 

- 8일 개인 작업 수행
- 9일 개인 작업 수행
- 10일 개인 작업 수행
- 11일 통합
- 12일 기능 구현 100% 완료 / 배포

## 4월 셋째주(코드 리팩토링, 문서 정리, 프론트 완성)
- [ ] 민우 : 데이터 이식, 통합 및 배포
- [ ] 규혁 : 웹, 단위, 성능 테스트, 작업물 개선, 문서 작업
- [ ] 대호 : 웹, 단위, 성능 테스트, 작업물 개선, 문서 작업
- [ ] 경민 : 검색 기능 통합, ppt, 리드미, 위키 작성

- 15일
- 16일
- 17일
- 18일
- 19일 프로젝트 최종 배포

## 4월 넷째주(최종, 발표 준비 및 마무리, PPT, 문서)
- [ ] 민우 :
- [ ] 규혁 : 
- [ ] 대호 :
- [ ] 경민 :

- 22일 PPT, 문서 정리, 발표 준비
- 23일 발표 준비
- 24일 발표 준비
- 25일 최종 발표

**Comment by minu1215** [comment]
App, MSA, 검색(AI), 관리자 페이지, 프론트 이쁘게
2 
3
4
5 배포

권한 정리, MSA, TEST, 인터페이스 정리 프론트 이쁘게
8
9
10
11
12 배포

코드 리팩토리, 문서 정리,  프론트 이쁘게
15
16
17
18
19 배포

22 ~ 24

**Comment by papercrane55123** [comment]
* 크롤링은 언제, 어느 데이터?(무비렌즈라는 데이터 셋, 영화 장르 등등 개선 / 우리는 사용해야 하는 것은 안에 있는 데이터이기 때문에 문장을 압축할 필요가 있고 얼마나 유사한지 카테고리를 묶고, 태그도 인풋으로 설계, 신경망 설계 또는 문서의 유사성을 찾는 알고리즘 구축. )
* nGrinder를 활용한 성능 테스트 진행 후 개선 작업.
* 깃헙 리드미, 위키 정리 필요
* 관리자 페이지 만들기
* MSA 찢기
* 코드 리펙토링
* 문서 정리

**Comment by papercrane55123** [comment]
1. 언제 통합할 것인가? - 통합한 후에도 프론트와 백엔드 등 고쳐야 할 부분이 많기 때문에 최대한 빨리 해야함.
완성해야만 통합하는건 아니다. 통합하고 추후 고쳐도 되는 것이다. 오히려 이 방법이 안전하다.
+TEST도 해야하기 때문에 이번주 안에는 
2. 남은 부분은 MSA, APP, AI, 관리자? - 각자 언제까지 할 수 있는가?
3. 테스트는 배포와 함께 바로 진행하자. 또한 문서로 남겨야 한다.
4. 프론트 부족한 부분 피드백하고 수정

* 강사님께 추가 산출물에 대해 여쭤보기 - 슬랙

**Comment by papercrane55123** [comment]
1. 언제 통합할 것인가?
2. 남은 부분은 MSA, APP, AI, 관리자? - 각자 언제까지 할 수 있는가?
3. 테스트는 통합과 함께 바로 진행하자. 또한 문서로 남겨야 한다.
4. 프론트 부족한 부분 피드백하고 수정

\* 강사님께 추가 산출물에 대해 여쭤보기 - 슬랙
답변 :  이제 남은건 코드랑 발표자료죠 코드는 지난 2차 배포와 함께 받았으니 정해진 산출물은 발표자료 입니다

**Comment by papercrane55123** [comment]
#### 추가 사항
* 크롤링은 언제, 어느 데이터?(무비렌즈라는 데이터 셋, 영화 장르 등등 개선 / 우리는 사용해야 하는 것은 안에 있는 데이터이기 때문에 문장을 압축할 필요가 있고 얼마나 유사한지 카테고리를 묶고, 태그도 인풋으로 설계, 신경망 설계 또는 문서의 유사성을 찾는 알고리즘 구축. )
* nGrinder를 활용한 성능 테스트 진행
* 문서 정리(깃헙 리드미, 위키 등)
