### ISSUE TITLE
[T1] 24.04.05 9회차 멘토링 정리

### ISSUE THREAD

**Issue by pdh4869** [HW-UMUL/main#95]
기획 단계에서 산출물 o, 평가 받음

다른 단계에서도 산출물 내야 함 (개발, 배포, 테스트 ? 등)
- 팀, 프로젝트 이름, 프론트/백 배포 url 있음

필요한것 
 - API 설계 문서(중점기술명세, 구현방식 기술)
 - 테스트 계획, 경과 보고서

필요 작업
- 프로젝트 기획
- 백엔드 설계 및 구축
- 프론트 설계 및 구축
- 시스템 통합

wbs 작성시 해야할 것
- 일정 작성 (기준 수립 - 최소, 최대 기간 등, 단위별(이틀, 일주일 등) 일정 수립),  목표 날짜 설정
- 일정 변경(딜레이 등)에 대한 대응 방안 수립
- 디자인 범위 설정
- 기능별 UI/UX 구성 <= 추가(개발과 나눠 작성)

- 협의만 하면 금방 할 수 있을 것 같다.

안드로이드 애플리케이션 관련
- 목표 달성 가능 여부
- 정확한 목표 설정 및 일정 맞추기 필요

기타 의견
- 프로필 업데이트시 업데이트 버튼을 입력창 오른쪽에 있으면 좋겠다
- 세부 기능 필요

**Comment by papercrane55123** [comment]
![LGTM](https://i.lgtm.fun/2qyn.gif)
